services:
  webui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "3001:8080"
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
    volumes:
      - webui-data:/app/backend/data
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama
    network_mode: "host"
    volumes:
      - ollama-data:/root/.ollama
      - .:/workspace
    working_dir: /workspace
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_MAX_LOADED_MODELS=3

volumes:
  webui-data:
  ollama-data: